name: Validate exercise
on: push
jobs:
    Validation:
      runs-on: ubuntu-latest
      steps:
        - name : Lint
          run: eslint --ext .jsx --fix src
        - name: Test
          run: vitest run
        - name: Deploy
          run: vite preview
